FROM python:3.11-slim
 
WORKDIR /app
 
RUN pip install --no-cache-dir \
    prometheus_client \
    yfinance \
    requests \
    pandas \
    numpy
 
COPY stocks_exporter.py .
 
EXPOSE 9878
 
CMD ["python", "-u", "stocks_exporter.py"]
